# Site settings
title: Jun's PR
description: Presentation Page
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://jun2-lee.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 준희
user_description: Web Backend 개발자를 목표로 하고 있습니다. <br> 주 사용 Framework는 Spring이고, 천천히 실력을 쌓아가고 있습니다.
user_title: 뉴비 개발자
email: ljh19980823@gmail.com
twitter_username: lorem_ipsum
github_username:  Jun2-Lee
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
