# Site settings
title: Jun's PR page
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jun2-lee.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 뉴비 개발자
user_description: 백엔드가 하고싶은 뉴비 개발자입니다!!
user_title: Newbie Developer
email: ljh19980823@gmail.com
# twitter_username: lorem_ipsum
instagram_username: mauriciourraco7
facebook_username: mauricio.urraco
linkedin_username: murraco
github_username:  murraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
